difficulty: advanced #adaptive/basic/intermediate/advanced
num_teams: 3
num_agents: 3
intermediate_num_agents: 5
model_info: Llama-3.3-70B-Instruct #'gpt-3.5', 'gpt-4', 'gpt-4o', 'gpt-4o-mini','gemini-pro-vision','gemini-pro','Qwen2.5-72B-Instruct'